module.exports = {
  SET_SETTINGS: 'SET_SETTINGS',
  CLEAR_CACHE: 'CLEAR_CACHE',
  TOGGLE_SETTING: 'TOGGLE_SETTING',
  SET_AUTHED: 'SET_AUTHED',
  SET_INITIALIZED: 'SET_INITIALIZED',
  SET_DARK_MODE: 'SET_DARK_MODE',
  SET_SIZE: 'SET_SIZE',
  SET_URL: 'SET_URL',
  TOGGLE_WINDOW_SIZE: 'TOGGLE_WINDOW_SIZE',
  TOGGLE_THEME: 'TOGGLE_THEME',
  SET_NIGHT_MODE: 'SET_NIGHT_MODE',
  MINIMIZE_ON_CLOSE: 'MINIMIZE_ON_CLOSE'
};
